---
title: "Procrastination & Academic Performance Example"
subtitle: "Jessica L. - Project (test)"
author: "KEY"
date: "`r Sys.Date()`"
output: 
    html_document:
      theme: sketchy
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

------------------------------------------------------------------------

### Data source (Kaggle: Procrastination & Academic Performance):

LINK: https://www.kaggle.com/datasets/borannogolder/procrastination-and-academic-performance/data

What is Kaggle? 

------------------------------------------------------------------------

```{r}

library(tidyverse)
library(janitor)
library(report)
library(gt)

source("load_plot_functions.R")

```

------------------------------------------------------------------------

### Read in data & clean

------------------------------------------------------------------------

```{r}

proc_data <- read_csv(here("data", "Procrastinate-Data.csv")) %>% 
  clean_names() %>% 
  select(timestamp, study_year,
   socio_econ = socio_economic_background,
   cgpa,
   assign_delay = assignment_delay_frequency,
   assign_submit_time = assignment_submission_timing,
   stress_proc = stress_due_to_procrastination,
   last_minute_prep = last_minute_exam_preparation,
   study_distract = study_session_distractions
  ) %>% 
  mutate(gpa = case_when(
    cgpa %in% "Below 2.50"  ~ 1,
    cgpa %in% "2.50 - 2.99" ~ 2,
    cgpa %in% "3.00 - 3.49" ~ 3,
    cgpa %in% "3.50 - 3.74" ~ 4,
    cgpa %in% "3.75 - 4.00" ~ 5
  )) %>% 
  mutate(submit_5 = case_when(
    assign_submit_time %in% "Never"  ~ 1,
    assign_submit_time %in% "Occasionally" ~ 2,
    assign_submit_time %in% "Sometimes" ~ 3,
    assign_submit_time %in% "Often" ~ 4,
    assign_submit_time %in% "Always" ~ 5 
  )) %>% 
  mutate(submit_2 = case_when(
    assign_submit_time %in% "Never"  ~ "Low",
    assign_submit_time %in% "Occasionally" ~ "Low",
    assign_submit_time %in% "Sometimes" ~ "Low",
    assign_submit_time %in% "Often" ~ "High",
    assign_submit_time %in% "Always" ~ "High"
  )) %>% 
  mutate(submit_2 = factor(submit_2,
                           levels = c("Low", "High"),
                           labels = c("Early Submissions", "Late Submissions"))) %>% 
  mutate(across(where(~ is.character(.x)), ~ as.factor(.x)))

```


------------------------------------------------------------------------

### Look at distributions

------------------------------------------------------------------------

Make a histogram
```{r}

hist_plot(
  data = proc_data,
  binwidth=1,
  x_var = gpa,
  x_label = "Grade Point Average",
  fill = "blue", color = "purple",
  break_min =0, break_max =5 , break_by = 1,
  mean_line = TRUE, median_line = TRUE,
  skew_value = TRUE, kurtosis_value = TRUE,
  title   = ""
)

```


Look at distributions by group
```{r}

plot_group_dist(
  data = proc_data,
  outcome = "gpa",
  group_var = "submit_2",
  title = "Is assign. Submission timing related to GPA?",
  subtitle = "Student Survey (N = 451)",
  colors = c("#0288b7", "#a90010"))

```

------------------------------------------------------------------------

### Look at associations using scatterplots

------------------------------------------------------------------------

```{r}
scatter_plot(
  data = proc_data,
  x_var = submit_5,
  x_label = "Assignment Submission Timing",
  y_var = gpa,
  y_label = "Grade Point Average",
  point_color = "darkgreen",
  corr_line = TRUE,
  title   = "Texts Sent vs. Received"
)
```




